"""
Signal dataclass for TrendSpec strategy framework.

Signals are the output of strategy logic and represent trading intentions.
The engine processes signals through the risk pipeline before broker execution.
"""

from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Signals represent the strategy's intention to buy or sell an instrument.
    They are processed by the risk pipeline before being submitted to the broker.

    Attributes:
        direction: BUY or SELL
        ticker: Display ticker/symbol (mutable, for human readability)
        instrument_id: Immutable internal ID (primary key)
        price: Price at which signal was generated (typically current close)
        trigger_value: Optional indicator/factor value that triggered the signal
        note: Optional human-readable note explaining the signal
        timestamp: Optional timestamp when signal was generated

    Example:
        >>> signal = Signal(
        ...     direction="BUY",
        ...     ticker="600000",
        ...     instrument_id="SH600000",
        ...     price=10.5,
        ...     trigger_value=20.0,  # MA20 value
        ...     note="Price crossed above MA20"
        ... )
    """

    direction: Literal["BUY", "SELL"]
    ticker: str
    instrument_id: str
    price: float
    trigger_value: float | None = None
    note: str | None = None
    shares: float | None = field(default=None, repr=False)
    timestamp: float | None = field(default=None, repr=False)
    extras: dict[str, Any] = field(default_factory=dict, repr=False)

    def __post_init__(self) -> None:
        """Validate signal after initialization."""
        if self.direction not in ("BUY", "SELL"):
            raise ValueError(f"Invalid direction: {self.direction}. Must be BUY or SELL")
        if self.price <= 0:
            raise ValueError(f"Price must be positive: {self.price}")

    def is_buy(self) -> bool:
        """Check if this is a buy signal."""
        return self.direction == "BUY"

    def is_sell(self) -> bool:
        """Check if this is a sell signal."""
        return self.direction == "SELL"


@dataclass
class SignalBatch:
    """
    Collection of signals generated in a single bar.

    Used to batch signals from a strategy's next() call for efficient processing.

    Attributes:
        signals: List of signals
        bar_date: Date of the bar that generated these signals
        strategy_name: Name of the strategy that generated the signals
    """

    signals: list[Signal]
    bar_date: str | None = None  # ISO date string
    strategy_name: str | None = None

    def __len__(self) -> int:
        return len(self.signals)

    def is_empty(self) -> bool:
        return len(self.signals) == 0

    def buy_signals(self) -> list[Signal]:
        """Get all buy signals."""
        return [s for s in self.signals if s.is_buy()]

    def sell_signals(self) -> list[Signal]:
        """Get all sell signals."""
        return [s for s in self.signals if s.is_sell()]
